/* AIGovOps Vendor RFI — expanded 2026 vendor landscape (single source of truth).
 * Researched June 2026 by aigovops-agent-vendor-rfi across five governance categories.
 * Neutral + gap-aware: pricing/oss are public-signal estimates (mostly custom-quoted enterprise);
 * several entries reflect recent M&A. The OT/IIoT category is honestly NOT AI-model governance —
 * it is the unfilled manufacturing gap. Source: docs/vendor-guide.html + 2025-2026 vendor research. */
const VENDOR_META = {
  lastReviewed: "2026-06-19",          // ISO date of the last catalog audit
  reviewedBy:   "aigovops-agent-vendor-rfi",
  cadenceDays:  90,                    // re-audit at least quarterly (enforced by .github/workflows/freshness.yml)
  source:       "docs/vendor-guide.html",
  note:         "Corrections welcome — open a vendor-correction issue. Ranking can't be bought; gaps aren't hidden."
};
const VENDOR_CATEGORIES = [
  {id:"grc",     label:"Compliance & AI GRC",        layer:"Audit & Policy",         note:"Audit, policy/obligation libraries, regulatory mapping, dashboards."},
  {id:"policy",  label:"Policy-as-code & Gates",     layer:"Gates & Controls",       note:"CI/CD + K8s + IaC enforcement and AI-agent tool control."},
  {id:"runtime", label:"Guardrails & Observability", layer:"Runtime Observability",  note:"Runtime interception, model/agent tracing, drift & safety."},
  {id:"ship",    label:"Code Shipping & Supply Chain",layer:"Shipping",              note:"AI-gen code, SCA, IaC, cloud posture, AI-BOM."},
  {id:"ot",      label:"OT / IIoT (the gap)",        layer:"OT / IIoT",              note:"OT security & asset visibility — NOT AI-model governance. The unfilled gap."}
];
const VENDORS = [
  // ── Compliance & AI GRC ───────────────────────────────────────────────────
  {cat:"grc", name:"Credo AI", best:"Policy-pack governance for regulated enterprises", gap:"Light on manufacturing / OT shop-floor context", oss:"partial", pricing:"Enterprise, $100K+/yr", frameworks:"EU AI Act, NIST AI RMF, ISO 42001, SOC 2", tags:["compliance","policy","inventory"]},
  {cat:"grc", name:"IBM watsonx.governance", best:"Unified governance across ML, GenAI & agentic AI", gap:"Heavy; best value inside the IBM/watsonx stack", oss:"no", pricing:"Enterprise, custom", frameworks:"EU AI Act, NIST, ISO 42001, SR 11-7 (12)", tags:["enterprise","risk","inventory"]},
  {cat:"grc", name:"OneTrust AI Governance", best:"AI inventory tied to existing privacy/GRC", gap:"AI module bolted onto a privacy suite; less ML-deep", oss:"no", pricing:"Enterprise, custom", frameworks:"EU AI Act, NIST, OECD, ISO 42001", tags:["compliance","inventory","dashboard"]},
  {cat:"grc", name:"Holistic AI", best:"Shadow-AI discovery + bias/risk testing", gap:"Discovery/testing over deep obligation libraries", oss:"no", pricing:"Enterprise, custom", frameworks:"EU AI Act, NIST, ISO 42001", tags:["audit","risk","inventory"]},
  {cat:"grc", name:"Saidot", best:"EU-built, AI-Act-native policy & control libraries", gap:"European focus; smaller US enterprise footprint", oss:"no", pricing:"Tiered subscription", frameworks:"EU AI Act, NIST (260+ risks, 600+ controls)", tags:["compliance","policy","risk"]},
  {cat:"grc", name:"Monitaur", best:"Controls-based ML assurance for regulated industries", gap:"Model-assurance depth over broad obligation mapping", oss:"no", pricing:"Enterprise, flexible", frameworks:"EU AI Act, NIST, ISO 42001", tags:["audit","risk","enterprise"]},
  {cat:"grc", name:"Trustible", best:"Expert-curated cross-framework control normalization", gap:"Governance layer only; no deep ML/pipeline integration", oss:"no", pricing:"Enterprise, custom", frameworks:"EU AI Act, NIST, ISO 42001, CO SB 205 (10+)", tags:["compliance","policy","dashboard"]},
  {cat:"grc", name:"ModelOp", best:"Evergreen AI inventory with lifecycle governance score", gap:"MLOps-heavy; integration effort to stand up", oss:"no", pricing:"Enterprise, custom", frameworks:"EU AI Act, NIST, ISO 42001", tags:["inventory","enterprise","dashboard"]},
  {cat:"grc", name:"Modulos", best:"ISO-42001-conformant governance graph w/ control reuse", gap:"Smaller vendor; lighter ecosystem breadth", oss:"no", pricing:"Enterprise, custom", frameworks:"EU AI Act, ISO 42001, NIST", tags:["compliance","policy","risk"]},
  {cat:"grc", name:"VerifyWise", best:"Self-hostable open-source AI governance", gap:"Younger; less turnkey at F100 scale", oss:"yes", pricing:"Free OSS + paid", frameworks:"EU AI Act, ISO 42001, NIST (20+)", tags:["open","compliance","audit"]},
  // ── Policy-as-code & Gates ────────────────────────────────────────────────
  {cat:"policy", name:"Open Policy Agent (OPA)", best:"De facto policy-as-code standard (Rego)", gap:"No native AI-agent/tool-call awareness; Rego curve", oss:"yes", pricing:"Apache-2.0 free", frameworks:"Framework-agnostic (CIS, custom)", tags:["policy","k8s","open"]},
  {cat:"policy", name:"Styra DAS / Enterprise OPA", best:"Managed control plane for OPA at scale", gap:"Commercial DAS sunsetting (2025); roadmap uncertain", oss:"partial", pricing:"OSS + enterprise", frameworks:"Framework-agnostic, compliance packs", tags:["policy","gates","k8s"]},
  {cat:"policy", name:"HashiCorp Sentinel", best:"Native IaC / Terraform deployment gates", gap:"Proprietary; scoped to HashiCorp, not agent control", oss:"no", pricing:"Per-tier enterprise", frameworks:"Framework-agnostic (cost, security)", tags:["policy","gates","infra"]},
  {cat:"policy", name:"Kyverno", best:"YAML-native Kubernetes policy (no Rego)", gap:"K8s-only; no app/agent-level authorization", oss:"yes", pricing:"Apache-2.0 free", frameworks:"Framework-agnostic (PSS, CIS, PCI)", tags:["policy","k8s","open"]},
  {cat:"policy", name:"OPA Gatekeeper (K8s)", best:"CNCF-graduated K8s admission control", gap:"Admission only; constraint-template overhead", oss:"yes", pricing:"Apache-2.0 free", frameworks:"Framework-agnostic (CIS, PSS)", tags:["policy","k8s","gates"]},
  {cat:"policy", name:"Cedar / Amazon Verified Permissions", best:"Provable fine-grained authz (PARC model)", gap:"AVP is AWS-managed; app-authz, not CI/infra gates", oss:"partial", pricing:"Cedar free; AVP pay-per-req", frameworks:"Framework-agnostic (RBAC/ABAC)", tags:["authz","agent-control","open"]},
  {cat:"policy", name:"Cerbos", best:"Decoupled authz with explicit MCP/agent support", gap:"App-layer authz; not a CI/IaC/admission gate", oss:"yes", pricing:"Apache-2.0 + Hub", frameworks:"RBAC/ABAC + MCP tool-call control", tags:["authz","agent-control","open"]},
  {cat:"policy", name:"Permit.io", best:"Low-code authz fronting OPA/OpenFGA/Cedar; AI access", gap:"Abstraction layer, not infra/deploy gating", oss:"partial", pricing:"Free tier + enterprise", frameworks:"RBAC/ABAC/ReBAC + MCP agent perms", tags:["authz","agent-control"]},
  {cat:"policy", name:"OpenFGA", best:"Scalable relationship-based (Zanzibar) authz", gap:"ReBAC modeling effort; no CI/agent-tooling layer", oss:"yes", pricing:"Apache-2.0 free", frameworks:"Framework-agnostic (ReBAC)", tags:["authz","open"]},
  {cat:"policy", name:"Oso", best:"Embeddable app authz via the Polar language", gap:"OSS lib deprecating toward Oso Cloud", oss:"partial", pricing:"OSS lib + Oso Cloud", frameworks:"RBAC/ReBAC/ABAC", tags:["authz","open"]},
  // ── Guardrails & Observability ────────────────────────────────────────────
  {cat:"runtime", name:"Fiddler AI", best:"Real-time guardrails + full AI observability", gap:"Heavyweight; enterprise-only commitment", oss:"no", pricing:"Enterprise, custom", frameworks:"NIST AI RMF, behavioral/safety", tags:["runtime","observability","guardrails"]},
  {cat:"runtime", name:"NVIDIA NeMo Guardrails", best:"Programmable in-app rails, self-hosted", gap:"Toolkit not platform; no dashboards", oss:"yes", pricing:"OSS (free)", frameworks:"Behavioral/safety", tags:["runtime","guardrails","open"]},
  {cat:"runtime", name:"Arize AI (Phoenix)", best:"OpenTelemetry agent tracing + evals", gap:"Eval/trace focus, lighter on inline blocking", oss:"partial", pricing:"OSS + cloud", frameworks:"OpenTelemetry, behavioral/safety", tags:["observability","agents","open"]},
  {cat:"runtime", name:"Lakera (Cisco AI Defense)", best:"Best-in-class prompt-injection/jailbreak blocking", gap:"Security-only; folded into Cisco procurement", oss:"no", pricing:"Enterprise, custom", frameworks:"OWASP LLM Top 10", tags:["runtime","security","guardrails"]},
  {cat:"runtime", name:"Protect AI (Palo Alto / Prisma AIRS)", best:"Runtime + supply-chain AI security suite", gap:"Absorbed into the Palo Alto platform", oss:"partial", pricing:"Enterprise, custom", frameworks:"OWASP LLM Top 10, MITRE ATLAS", tags:["runtime","security","guardrails"]},
  {cat:"runtime", name:"Arthur AI", best:"LLM firewall + observability + open engine", gap:"Smaller vendor; firewall depth varies", oss:"partial", pricing:"OSS + enterprise", frameworks:"NIST AI RMF, behavioral/safety", tags:["runtime","observability","guardrails"]},
  {cat:"runtime", name:"Guardrails AI", best:"Open validator framework (Guardrails Hub)", gap:"DIY assembly; managed tier maturing", oss:"yes", pricing:"OSS + Pro", frameworks:"Behavioral/safety", tags:["guardrails","open","runtime"]},
  {cat:"runtime", name:"Langfuse", best:"MIT-licensed self-hosted LLM/agent tracing", gap:"Observability/evals only; not an enforcer", oss:"yes", pricing:"OSS + cloud", frameworks:"OpenTelemetry, behavioral/safety", tags:["observability","dashboard","open"]},
  {cat:"runtime", name:"Galileo", best:"Luna eval models for hallucination/agent metrics", gap:"Eval-centric; Cisco acquisition in progress", oss:"no", pricing:"Free tier + enterprise", frameworks:"Behavioral/safety", tags:["observability","agents","guardrails"]},
  {cat:"runtime", name:"HiddenLayer", best:"Agentless runtime defense + AI-BOM/model security", gap:"MLSecOps focus; light on app observability", oss:"no", pricing:"Enterprise, custom", frameworks:"MITRE ATLAS, OWASP LLM Top 10", tags:["runtime","security","agents"]},
  // ── Code Shipping & Supply Chain ──────────────────────────────────────────
  {cat:"ship", name:"Snyk", best:"Developer-first AppSec with AI-BOM", gap:"Breadth over depth; runtime/cloud weaker than SCA", oss:"partial", pricing:"Free tier; per-dev", frameworks:"OWASP Top 10, OWASP LLM Top 10", tags:["shipping","sca","ai-bom"]},
  {cat:"ship", name:"Wiz", best:"Cloud posture w/ AI-SPM + Shadow-AI discovery", gap:"Cloud-centric; thin on pre-commit code/SCA", oss:"no", pricing:"Enterprise, workload-based", frameworks:"CIS, NIST, OWASP LLM Top 10", tags:["cloud","security","ai-bom"]},
  {cat:"ship", name:"Endor Labs", best:"Reachability-based SCA, code-to-container", gap:"Younger; smaller enterprise footprint", oss:"partial", pricing:"Free tier; per-dev", frameworks:"OWASP LLM Top 10, SLSA, OpenSSF", tags:["sca","shipping","ai-bom"]},
  {cat:"ship", name:"Semgrep", best:"Fast hybrid SAST (rules + AI) for AI-gen code", gap:"Less deep dataflow; not cloud/runtime", oss:"yes", pricing:"Free OSS; per-dev", frameworks:"OWASP Top 10, CWE", tags:["dev","security","open"]},
  {cat:"ship", name:"Checkmarx", best:"Enterprise SAST/DAST/SCA/IaC + agentic AppSec", gap:"Heavyweight; legacy complexity, cost", oss:"no", pricing:"Enterprise, custom", frameworks:"OWASP Top 10, PCI, NIST", tags:["shipping","security","iac"]},
  {cat:"ship", name:"GitHub Advanced Security", best:"Native CodeQL/Dependabot/secret scanning", gap:"GitHub-only; not full ASPM or AI-BOM", oss:"partial", pricing:"~$19-30/committer/mo", frameworks:"CWE, OWASP Top 10", tags:["dev","sca","security"]},
  {cat:"ship", name:"Socket", best:"Behavioral/AI detection of malicious packages", gap:"Supply-chain only; not SAST/cloud", oss:"partial", pricing:"Free OSS; ~$25/seat", frameworks:"Supply-chain risk model", tags:["sca","security","dev"]},
  {cat:"ship", name:"Chainguard", best:"Zero-CVE hardened images w/ SLSA provenance", gap:"Image/runtime hardening, not code or AI-specific", oss:"partial", pricing:"Free tier; enterprise", frameworks:"SLSA, Sigstore, SBOM", tags:["shipping","cloud","open"]},
  {cat:"ship", name:"Aqua Security", best:"CNAPP code-to-cloud + OSS Trivy scanner", gap:"Cloud/container focus; not AI-governance-specific", oss:"yes", pricing:"Enterprise; free Trivy", frameworks:"CIS, NIST, SLSA", tags:["cloud","iac","open"]},
  {cat:"ship", name:"Apiiro", best:"Deep ASPM risk-graph for AI-driven code velocity", gap:"Posture/prioritization; relies on scanners for findings", oss:"no", pricing:"Enterprise, custom", frameworks:"OWASP Top 10, OWASP LLM Top 10", tags:["security","shipping","ai-bom"]},
  // ── OT / IIoT (the gap — OT security, NOT AI-model governance) ─────────────
  {cat:"ot", name:"Claroty (xDome / CTD)", best:"Deep CPS asset visibility for industrial + healthcare", gap:"No AI/LLM-model governance; secures devices, not agents", oss:"no", pricing:"Enterprise quote; six-figure", frameworks:"IEC 62443, NIST CSF, NERC CIP", tags:["ot","scada","asset-visibility"]},
  {cat:"ot", name:"Dragos", best:"ICS threat detection backed by OT threat-intel", gap:"Threat-hunting focus; no AI-model oversight", oss:"no", pricing:"Enterprise quote; premium", frameworks:"IEC 62443, NIST CSF, NERC CIP", tags:["ot","scada","security"]},
  {cat:"ot", name:"Nozomi Networks", best:"OT/IoT visibility + anomaly detection", gap:"AI used for detection, not governance of AI models", oss:"no", pricing:"Subscription", frameworks:"IEC 62443, NIST CSF", tags:["ot","iiot","asset-visibility"]},
  {cat:"ot", name:"Armis Centrix (ServiceNow)", best:"Agentless cross-domain asset intelligence", gap:"Exposure mgmt, not AI-model governance", oss:"no", pricing:"Enterprise quote; SaaS", frameworks:"IEC 62443, NIST CSF", tags:["ot","iiot","asset-visibility"]},
  {cat:"ot", name:"Tenable OT Security", best:"OT vuln management + asset inventory", gap:"Vulnerability lens only; no AI governance", oss:"no", pricing:"Per-asset subscription", frameworks:"IEC 62443-3-3, NIST CSF", tags:["ot","scada","security"]},
  {cat:"ot", name:"Forescout (4D)", best:"Asset intel + active control/segmentation", gap:"Network control, not model governance", oss:"no", pricing:"Enterprise quote; device-based", frameworks:"IEC 62443, NIST CSF", tags:["ot","iiot","security"]},
  {cat:"ot", name:"Microsoft Defender for IoT", best:"Agentless OT monitoring into Defender XDR", gap:"OT detection; AI governance lives in Purview", oss:"no", pricing:"Per-device, Azure", frameworks:"NIST CSF, IEC 62443", tags:["ot","iiot","security"]},
  {cat:"ot", name:"TXOne Networks", best:"OT zero-trust endpoint/network protection", gap:"Endpoint hardening, not AI-model oversight", oss:"no", pricing:"Enterprise quote; per-endpoint", frameworks:"IEC 62443-4-1 certified", tags:["ot","scada","manufacturing"]},
  {cat:"ot", name:"Cisco Cyber Vision", best:"OT visibility native to Cisco switches", gap:"Network-centric; no AI governance", oss:"no", pricing:"Hardware/license bundle", frameworks:"IEC 62443, NIST CSF", tags:["ot","iiot","asset-visibility"]},
  {cat:"ot", name:"Rockwell / Verve (SecureOT)", best:"Vendor-neutral OT endpoint mgmt + remediation", gap:"Asset/vuln remediation, not AI-model governance", oss:"no", pricing:"Enterprise quote; services-led", frameworks:"IEC 62443, NIST CSF", tags:["ot","manufacturing","asset-visibility"]}
];
if (typeof module !== "undefined") module.exports = { VENDOR_CATEGORIES, VENDORS };
